### ISSUE TITLE
Switch to yaml.safe_load() 

### ISSUE THREAD

**Issue by jderusse** [Numergy/yoda#21]
Your code has a security issue: https://github.com/Numergy/yoda/blob/master/yoda/config.py#L33

Explanation: http://nedbatchelder.com/blog/201302/war_is_peace.html

**Comment by Sliim** [comment]
Thank you Jeremy :) 

I merged @PierreRambaud pull request, now Yoda use yaml.safe_load() method instead yaml.load() :)
